name: landlab_docs
channels:
  - conda-forge
dependencies:
- python==3.6
- numpy
- pandas
- pandoc
- pip
- sphinx>=1.5.1
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
    - sphinxcontrib_github_alt
